
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    develop:
      watch:
        - path: ./package.json
          action: rebuild
        - path: ./next.config.js
          action: rebuild
        - path: './package-lock.json'
          action: rebuild
        - path: .
          target: /app
          action: sync
    environment:
      - NODE_ENV=development
      - DATABASE_URL=mysql://root:admin@db:3306/next-sched
    depends_on:
            db:
                condition: service_healthy
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next

  db:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT=root1
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=next-sched
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "db"]
        timeout: 20s
        retries: 10
    restart: unless-stopped
  phpmyadmin:
    image: phpmyadmin:5.2.1-apache
    ports:
      - 127.0.0.1:9995:80
    environment:
      - PMA_ARBITRARY=0
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=admin
      - UPLOAD_LIMIT=512M
    depends_on:
      - db
volumes:
  mysql-data: